/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ApiVideoDriveIdRouteImport } from './routes/api/video/$driveId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoDriveIdRoute = ApiVideoDriveIdRouteImport.update({
  id: '/api/video/$driveId',
  path: '/api/video/$driveId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/video/$driveId': typeof ApiVideoDriveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/video/$driveId': typeof ApiVideoDriveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/work/$slug': typeof WorkSlugRoute
  '/api/video/$driveId': typeof ApiVideoDriveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/work/$slug' | '/api/video/$driveId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/work/$slug' | '/api/video/$driveId'
  id: '__root__' | '/' | '/work/$slug' | '/api/video/$driveId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkSlugRoute: typeof WorkSlugRoute
  ApiVideoDriveIdRoute: typeof ApiVideoDriveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video/$driveId': {
      id: '/api/video/$driveId'
      path: '/api/video/$driveId'
      fullPath: '/api/video/$driveId'
      preLoaderRoute: typeof ApiVideoDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkSlugRoute: WorkSlugRoute,
  ApiVideoDriveIdRoute: ApiVideoDriveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
